# workflow

name: "UniVerse"

on:
    push:
        branches:
            [main,master]

jobs:
    build:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v3
            - name: Node version
              run: node --version